#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00
#SBATCH --mem=4GB

#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report

#python main.py
singularity exec docker://aunnikri642/app-freesurfer-mne-source-recon python3 main.py


